### ISSUE TITLE
Notification to Manager for Pending Approvals

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#88] opened 2019-07-19 02:24 UTC
If an asset is assigned or unassigned, devise a way to notify the manager.
Applies to all features where manager approval is required.

You may add a section in the Home (dashboard) for Manager Pending Approvals if email notification is complicated given that it will need server information.

**Comment by jhunellbarcenas** [comment] 2019-07-26 04:31
Considered as duplicate of #21

**Comment by charissasylim** [comment] 2019-10-16 01:08
By Harvey -
Create a notification for the employees who have pending leaves to be file.
The notification can be view in 'Attendance' button.

**Comment by charissasylim** [comment] 2020-03-09 02:59
@jester0123 Email notif to be sent at the following instances.
1. Missing Entry in Resource Plan
2. Missing Weekly Status Report
3. When asset inventory movement needs approval
4. When contact list or skills matrix has not been updated after 1st day of the month
5. Reminder to do in Workplace Audit

**Closed as completed** 2020-05-18 03:02 UTC
Labels: Enhancement, Medium Priority, For QA Testing
