### ISSUE TITLE
Task - Assign task project field has a black drop down list

### ISSUE THREAD

**Issue by chloecastillo** [rsx-labs/aide-frontend#195] opened 2019-08-27 07:01 UTC
**Describe the bug**
After selecting the employee to assign task, project to link the task cannot be selected as it has black drop down list.

**To Reproduce**
1. Go to 'Task'
2. Click on '+' sign
3. Enter details of the task
4. Select The Project Drop down list

**Expected behavior**
Available projects is listed in the Project Drop down list field.

**Screenshots**
![Add Task](https://user-images.githubusercontent.com/53286096/63748175-70f4df80-c8db-11e9-83c1-9c53684a7f98.jpg)

V2.6

**Comment by jhunellbarcenas** [comment] 2019-08-29 09:02
@chloecastillo This is not a bug. You are seeing this because you haven't added any projects for your team (QA). This drop down list gets all the projects for your team (QA).

**Comment by jhunellbarcenas** [comment] 2019-08-29 09:03
@chloecastillo Please try to add first a project then get back to this and see if it still occurs.

**Comment by jhunellbarcenas** [comment] 2019-08-29 09:04
Considered as closed. Can we close this? @charissasylim

**Closed as completed** 2019-08-30 05:41 UTC
Labels: Bug
