### ISSUE TITLE
[Email Verfication] Received Pop up window: Failure Sending Mail

### ISSUE THREAD

**Issue by vanchsalvador** [rsx-labs/aide-frontend#252] opened 2019-09-30 02:11 UTC
Precondition: Outlook is NOT Running 
Scenario Summary: 
1. In Email Verification Window input <personal email> then click "Send" button. An Access Code window appeared. 
2. Close the Access Code window by pressing "OK" button
or by pressing [x] on the upper right of the wndow

Actual: 
Wait for about 1 minute and a pop up message appeared "Failure sending mail" with "OK" button.

Expected: 
There should be no prompt window for Failure Sending Mail.

Note: We did not encounter this on the previous version

**Comment by charissasylim** [comment] 2019-10-02 00:57
@vanchsalvador @ellaineronquillo is this a duplicate of #256

**Comment by vanchsalvador** [comment] 2019-10-02 01:55
@charissasylim yes they are the same please close this one po.Thank you

**Comment by vanchsalvador** [comment] 2019-10-02 01:59
already closed this ticket. same with  #256

**Closed as completed** 2019-10-02 01:59 UTC
Labels: Question
