### ISSUE TITLE
[Task] Pages are still counted even without data/ pages are blank

### ISSUE THREAD

**Issue by ellaineronquillo** [rsx-labs/aide-frontend#268] opened 2019-10-01 07:31 UTC
**Describe the bug**
Pages are still counted even without data/ pages are blank

**To Reproduce**
[1] From Home / Dashboard, click the "Task" on the bottom panel
[2] Click the (+) button to add task
[3] Fill up the required fields then click "Create" button
[4] Click the arrow to view the pages

**Expected behavior**
Pages without data should not be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/54298100/65942759-88863180-e460-11e9-8745-b59ea9f51739.png)

![image](https://user-images.githubusercontent.com/54298100/65942764-8ae88b80-e460-11e9-81fe-7590da822d56.png)

**Version**
 - Version [2.7.1]

**Comment by charissasylim** [comment] 2019-10-02 00:14
duplicate of #243

**Closed as completed by charissasylim** 2019-10-02 00:14 UTC
Labels: Bug
