### ISSUE TITLE
[Contact List] Unable to edit the work shift for some employees

### ISSUE THREAD

**Issue by trashvin** [rsx-labs/aide-frontend#646] opened 2020-06-24 02:22 UTC
**Describe the bug**
Description from helpdesk : Work shift cannot be updated for Grace Singian

**To Reproduce**
In Contact List, edit Grace Singian and update shift to Flexi. 
Click Update and a pop up message "Contacts have been updated". 
click OK. 
When viewed again, the shift is still Semi-flex

**Expected behavior**
It should update the workshift schedule

**Version (please complete the following information):**
 - Version 3.3.7

**Additional context**
This can be reproduced in the dev env

**Comment by charissasylim** [comment] 2020-07-08 05:25
Fixed 3.3.8

**Comment by charissasylim** [comment] 2020-07-17 02:17
Reopened since issue still exists in 3.3.8

**Comment by charissasylim** [comment] 2020-08-06 07:57
confirmed fixed by jiji 3.3.9

**Closed as completed by charissasylim** 2020-08-06 07:57 UTC
Labels: Bug, High Priority, For QA Testing, From Helpdesk
