### ISSUE TITLE
Add asterisk(*) on the fields that are Mandatory

### ISSUE THREAD

**Issue by chloecastillo** [rsx-labs/aide-frontend#105] opened 2019-07-25 07:54 UTC
Asterisk as an identifier for Mandatory/Required fields make the users aware of the items they need to fill-up. This prevents them from go back and forth to the screen wondering what else needs to be entered.

**Comment by jhunellbarcenas** [comment] 2019-07-25 10:16
Duplicate of #93 
@chloecastillo

**Comment by jhunellbarcenas** [comment] 2019-08-01 09:28
Fixed. Ready for v2.6

**Closed as completed by jhunellbarcenas** 2019-08-01 09:28 UTC
Labels: Duplicate, Enhancement
